### ISSUE TITLE
Body validation not working

### ISSUE THREAD

**Issue by webstorm** [maxnachlinger/restify-joi-middleware#15]
Hello, I used snippet given on example, and while trying to validate a post request, it is not validating body param "name" and route handler is throwing Typeerror
```
Exception has occurred: TypeError
TypeError: Cannot read property 'name' of undefined
```
Here is the server code used
```
const Joi = require('joi')
const restify = require('restify')
const validator = require('restify-joi-middleware')

const server = restify.createServer();
server.use(restify.acceptParser(server.acceptable));
server.use(restify.authorizationParser());
server.use(restify.dateParser());
server.use(restify.queryParser());
server.use(restify.jsonp());
server.use(restify.gzipResponse());
server.use(restify.bodyParser());



// you can pass along all the joi options here
server.use(validator())


// additional middleware etc

server.get({
    path: '/:id',
    validation: {
        params: {
            id: Joi.number().min(0).required()
        }
    }
}, (req, res, next) => {
    res.send(200, { id: req.params.id })
    next()
})

server.post({
    path: '/',
    validation: {
        body: {
            name: Joi.string().required()
        }
    }
}, (req, res, next) => {
    res.send(201, { id: 1, name: req.body.name })
    next()
})

server.put({
    path: '/:id',
    // Joi.object().keys({}) schemas work too
    validation: Joi.object().keys({
        params: {
            id: Joi.number().min(0).required()
        },
        body: {
            id: Joi.number().min(0).required(),
            name: Joi.string().required()
        }
    }).assert('params.id', Joi.ref('body.id'))
}, (req, res, next) => {
    res.send(200, { id: 1, name: req.body.name })
    next()
});

server.listen(0,0,function() {
    console.log(`server listening on ${server.address().port}`);
});
```

**Comment by maxnachlinger** [comment]
Thanks for filing this issue, could you send along the full stack-trace of the error you're getting? As well as the version of restify you're using?

**Comment by maxnachlinger** [comment]
Using the above code, the following works just fine:
```shell
# install deps
npm i joi restify restify-joi-middleware --save

# created index.js with the server code you shared

node index.js # start server

# test a good post

curl -X POST \
-H 'accept: application/json' \
-d '{ "name": "test-name" }' \
http://localhost:59275/ 

# returns {"id":1,"name":"test-name"}

# test a bad post

curl -X POST \
-H 'accept: application/json' \
-d '{ "name": 1234 }' \
http://localhost:59275/ 

# returns {"code":"BadRequest","message":"","data":[{"message":"\"name\" must be a string","path":"body.name","type":"string.base","context":{"value":12,"key":"name"}}]}
```
So I guess I'm having trouble reproducing this :)

**Comment by webstorm** [comment]
Hi, Thank you for writing back. 
Here is stack trace
```
TypeError: Cannot read property 'name' of undefined
    at Server.server.post (/home/parijat/sandbox/test/index.js:44:46)
    at next (/home/parijat/sandbox/test/node_modules/restify/lib/server.js:912:30)
    at f (/home/parijat/sandbox/test/node_modules/once/once.js:25:25)
    at Server.<anonymous> (/home/parijat/sandbox/test/node_modules/restify-joi-middleware/index.js:57:3)
    at next (/home/parijat/sandbox/test/node_modules/restify/lib/server.js:912:30)
    at f (/home/parijat/sandbox/test/node_modules/once/once.js:25:25)
    at Server.parseBody (/home/parijat/sandbox/test/node_modules/restify/lib/plugins/body_parser.js:58:13)
    at next (/home/parijat/sandbox/test/node_modules/restify/lib/server.js:912:30)
    at f (/home/parijat/sandbox/test/node_modules/once/once.js:25:25)
    at Server.readBody (/home/parijat/sandbox/test/node_modules/restify/lib/plugins/body_reader.js:74:13)

````

also my package.json file looks like
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "joi": "^10.5.2",
    "restify": "^4.3.0",
    "restify-joi-middleware": "^2.1.0"
  },
  "devDependencies": {},
  "scripts": {
    "start": "node index.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```

Versions of packages
```
restify: 4.3.0
restify-joi-middleware: 2.1.0
joi: 10.5.2
```
Hope this helps tracking down source of error

**Comment by maxnachlinger** [comment]
Ah I see it, you need to use the bodyParser middleware to get `req.body`, e.g.
```javascript
server.use(restify.bodyParser());
```

**Comment by webstorm** [comment]
Sure. 

```
const fs = require('fs');
const Joi = require('joi')
const restify = require('restify')
const validator = require('restify-joi-middleware')

const server = restify.createServer();
server.use(restify.acceptParser(server.acceptable));
server.use(restify.authorizationParser());
server.use(restify.dateParser());
server.use(restify.queryParser());
server.use(restify.jsonp());
server.use(restify.gzipResponse());
server.use(restify.bodyParser());



// you can pass along all the joi options here
server.use(validator())


// additional middleware etc

server.get({
    path: '/:id',
    validation: {
        params: {
            id: Joi.number().min(0).required()
        }
    }
}, (req, res, next) => {
    res.send(200, { id: req.params.id })
    next()
})

server.post({
    path: '/',
    validation: {
        body: {
            name: Joi.string().required()
        }
    }
}, (req, res, next) => {
    try {
        res.send(201, { id: 1, name: req.body.name })
        next()
    } catch(e) {
        fs.writeFileSync('trace.txt', e.stack);
    }
})

server.put({
    path: '/:id',
    // Joi.object().keys({}) schemas work too
    validation: Joi.object().keys({
        params: {
            id: Joi.number().min(0).required()
        },
        body: {
            id: Joi.number().min(0).required(),
            name: Joi.string().required()
        }
    }).assert('params.id', Joi.ref('body.id'))
}, (req, res, next) => {
    res.send(200, { id: 1, name: req.body.name })
    next()
});

server.listen(0,0,function() {
    console.log(`server listening on ${server.address().port}`);
});
```

**Comment by maxnachlinger** [comment]
Still not able to reproduce using the above code, this passes:
(modified the above to run on port 9000)
```javascript
server.listen(9000, () => {
    console.log(`server listening on ${server.address().port}`);
});
```
This curl works:
```shell
curl -X POST -H 'accept: application/json' -d '{ "name": "test-name" }' http://localhost:9000/
# returns {"id":1,"name":"test-name"}
```

**Comment by webstorm** [comment]
Hi, Please remove trycatch  from post handler and send no data in post request. What i think, it should be triggering validation error in middleware in case of empty body and  request handler shouldn't be reached.
I used 
```
curl -X POST -H 'accept: application/json' -d '' http://localhost:9000/
```
to send post request and it came back with 
```
{"code":"InternalError","message":"Cannot read property 'name' of undefined"}
```

**Comment by maxnachlinger** [comment]
I see, you've not set `body` itself as required. Try this:
```javascript
server.post({
  path: '/',
  validation: {
    body: Joi.object().keys({
      name: Joi.string().required()
    }).required()
  }
}, (req, res, next) => {
  res.send(201, { id: 1, name: req.body.name })
  next()
})
```

**Comment by maxnachlinger** [comment]
Please re-open this issue if the above schema fix doesn't work.

**Comment by webstorm** [comment]
thank you. this worked.
