### ISSUE TITLE
Error in concat to default keys to validate

### ISSUE THREAD

**Issue by carvalhoviniciusluiz** [maxnachlinger/restify-joi-middleware#38]
Hi!
I have the following validation.
```javascript
const validation = {
  params: {
    registration_token: Joi.string()
  },
  body: {
    payload: Joi.object().keys({
      email: Joi.string().email().required(),
      password: Joi.string().min(6).max(15).required()
    }).required()
  }
}
```

```javascript
server.put({ path: '/registration/:registration_token', validation }, (req, res, next) => { res.json(200) })
```
when I run the validation, the following exception appears
```
{ ValidationError: child "body" fails because ["body" is required]
    at Object.exports.process (~/project/node_modules/restify-joi-middleware/node_modules/joi/lib/errors.js:190:19)
    at internals.Object._validateWithOptions (~/project/node_modules/restify-joi-middleware/node_modules/joi/lib/types/any/index.js:663:31)
    at module.exports.internals.Any.root.validate (~/project/node_modules/restify-joi-middleware/node_modules/joi/lib/index.js:139:23)
    at Server.<anonymous> (~/project/node_modules/restify-joi-middleware/index.js:41:22)
    at next (~/project/node_modules/restify/lib/server.js:1125:29)
    at f (~/project/node_modules/once/once.js:36:25)
    at Server.restifyResponseHeaders (~/project/node_modules/restify/lib/plugins/fullResponse.js:75:16)
    at next (~/project/node_modules/restify/lib/server.js:1125:29)
    at f (~/project/node_modules/once/once.js:36:25)
    at Server.parseQueryString (~/project/node_modules/restify/lib/plugins/query.js:53:20)
    at next (~/project/node_modules/restify/lib/server.js:1125:29)
    at f (~/project/node_modules/once/once.js:36:25)
    at Server.parseAccept (~/project/node_modules/restify/lib/plugins/accept.js:51:13)
    at next (~/project/node_modules/restify/lib/server.js:1125:29)
    at f (~/project/node_modules/once/once.js:36:25)
    at Server.parseJson (~/project/node_modules/restify/lib/plugins/jsonBodyParser.js:32:20)
    at next (~/project/node_modules/restify/lib/server.js:1125:29)
    at f (~/project/node_modules/once/once.js:36:25)
    at f (~/project/node_modules/once/once.js:25:25)
    at Server.readBody (~/project/node_modules/restify/lib/plugins/bodyReader.js:87:13)
    at next (~/project/node_modules/restify/lib/server.js:1125:29)
    at f (~/project/node_modules/once/once.js:36:25)
    at Server._run (~/project/node_modules/restify/lib/server.js:1179:16)
    at _route (~/project/node_modules/restify/lib/server.js:825:14)
    at onRoute (~/project/node_modules/restify/lib/server.js:939:24)
    at Router.find (~/project/node_modules/restify/lib/router.js:551:9)
    at Server._route (~/project/node_modules/restify/lib/server.js:922:28)
    at Server._routeAndRun (~/project/node_modules/restify/lib/server.js:816:10)
    at Server._handle (~/project/node_modules/restify/lib/server.js:863:14)
    at Server.onRequest (~/project/node_modules/restify/lib/server.js:214:14)
    at emitTwo (events.js:126:13)
    at Server.emit (events.js:214:7)
    at parserOnIncoming (_http_server.js:602:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
  isJoi: true,
  name: 'ValidationError',
  details:
   [ { message: '"body" is required',
       path: [Array],
       type: 'any.required',
       context: [Object] } ],
  _object: { body: undefined },
  annotate: [Function] }
```
I made the modifications to leave the validation similar to the example,  something like
```javascript
const validation = {
  params: Joi.object().keys({
    registration_token: Joi.string()
  }).required(),
  body: Joi.object().keys({
    payload: Joi.object().keys({
      email: Joi.string().email().required(),
      password: Joi.string().min(6).max(15).required()
    }).required()
  }).required()
}
```
and it did not solve!

**Comment by carvalhoviniciusluiz** [comment]
at this point in the code,
https://github.com/maxnachlinger/restify-joi-middleware/blob/f34c7d4d17696befdc723001e570fd71ea5663e1/index.js#L37

the value that comes from req contains the value of body as well
```
params { 
  registration_token: '123abc',
  payload: { password: 'secret', email: 'email@email' } 
}
```
And this does the validation become incorrect :(

**Comment by maxnachlinger** [comment]
Thanks for reaching out, I should be able to have a look in a few hours. For now, try writing a test to reproduce your issue  - you add a new test below this one: https://github.com/maxnachlinger/restify-joi-middleware/blob/master/tests/validationTests.js#L6

**Comment by maxnachlinger** [comment]
@carvalhoviniciusluiz would you mind running the new test here and telling me if it passes for you? https://github.com/maxnachlinger/restify-joi-middleware/pull/39/files

**Comment by carvalhoviniciusluiz** [comment]
@maxnachlinger the req parameter here at that point in the code

https://github.com/maxnachlinger/restify-joi-middleware/blob/f34c7d4d17696befdc723001e570fd71ea5663e1/index.js#L37

when it is req['params'], the value of the req['body'] comes concatenated.
the behavior to test this error should be like this:

```
  const req = {
    body: {
      payload: {
        email: 'test@test.com',
        password: 'test-password'
      }
    },
    params: {
      registration_token: 'test-token',
      payload: {
        email: 'test@test.com',
        password: 'test-password'
      }
    },
    route: {
      validation: Joi.object().keys({
        params: Joi.object().keys({
          registration_token: Joi.string()
        }).required(),
        body: Joi.object().keys({
          payload: Joi.object().keys({
            email: Joi.string().email().required(),
            password: Joi.string().min(6).max(15).required()
          }).required()
        }).required()
      })
    }
  }
```
you can see this behavior by putting a console.log(req[key]) above line 37 in the index.js file

I understand that the error is happening because of allowUnknown=true, so in this case, it is not allowed to use allowUnknown: false

```javascript
server.use(validator({
    allowUnknown: false
})
```

can server.js interfere with the configuration of the req parameter?  I'm not using bodyParser
```javascript
/**
  * Middleware
  */
server.use(restify.plugins.jsonBodyParser({ mapParams: true }))
server.use(restify.plugins.acceptParser(server.acceptable))
server.use(restify.plugins.queryParser({ mapParams: true }))
// server.use(restify.plugins.bodyParser({ mapParams: false }))
server.use(restify.plugins.fullResponse())
```

**Comment by maxnachlinger** [comment]
Actually this seems wrong:
```javascript
server.use(restify.plugins.jsonBodyParser({ mapParams: true }))
```
Based on the [restify plugin docs](http://restify.com/docs/plugins-api/#bodyparser), `bodyParser` is what you want, it will use the `jsonBodyParser` internally if the request comes in with a`Content-Type` header of `application/json`.Also setting `mapParams: true` is copying the parsed post body values onto req.params, which is probably not what you want. 

The  `mapParams: true` setting in the `queryParser` middleware will also cause problems, it will copy `key=values` pairs from the query string into `{key: value}` keys in `req.params` too. 

Would you mind trying this set of middleware and seeing if that fixes your issue?
```javascript
server.use(restify.plugins.acceptParser(server.acceptable))
server.use(restify.plugins.queryParser())
server.use(restify.plugins.bodyParser())
server.use(restify.plugins.fullResponse())
```

**Comment by carvalhoviniciusluiz** [comment]
You're correct, the tests passed this time without problems.
Thanks a lot for the help :)
