### ISSUE TITLE
Version 5.0.0 incompatible with Joi version 14.3.1 when using assert

### ISSUE THREAD

**Issue by TunstallC** [maxnachlinger/restify-joi-middleware#57]
Using the below package.json and the server.js file from the example folder, and running the test command of 
`curl -X PUT -H "Content-Type: application/json" -d '{"id":1,"name":"Max"}' http://127.00.1:8080/2` 

causes the server to crash with the error below.

package.json:
```
{
  "name": "restify-test",
  "version": "1.0.0",
  "dependencies": {
    "joi": "^14.0.0",
    "restify": "^7.2.2",
    "restify-errors": "^6.1.1",
    "restify-joi-middleware": "^5.0.0"
  }
}
```
error:
```
/Documents/restify-test/node_modules/restify-joi-middleware/node_modules/hoek/lib/index.js:736
    throw new Assert.AssertionError({
    ^

AssertionError [ERR_ASSERTION]: you must provide a joi schema
    at module.exports.internals.Any.root.reach (/Documents/restify-test/node_modules/restify-joi-middleware/node_modules/joi/lib/index.js:200:14)
    at keysToValidate.reduce (/Documents/restify-test/node_modules/restify-joi-middleware/index.js:88:18)
    at Array.reduce (<anonymous>)
    at /Documents/restify-test/node_modules/restify-joi-middleware/index.js:83:39
    at call (/Documents/restify-test/node_modules/restify/lib/chain.js:164:9)
    at next (/Documents/restify-test/node_modules/restify/lib/chain.js:120:9)
    at next (/Documents/restify-test/node_modules/restify/lib/chain.js:155:9)
    at gzip (/Documents/restify-test/node_modules/restify/lib/plugins/gzip.js:55:13)
    at call (/Documents/restify-test/node_modules/restify/lib/chain.js:164:9)
    at next (/Documents/restify-test/node_modules/restify/lib/chain.js:120:9)
```

Using the latest commit of restify-joi-middleware on the master branch fixes this issue, so it would be awesome if you could publish a new version with the latest changes to master.

**Comment by maxnachlinger** [comment]
Thanks for reaching out and filing such a detailed issue. Please give version `5.0.1` a go and let me know if it works for you.

**Comment by TunstallC** [comment]
👍 Looks good, thank you for the super quick response and update!
